# To use this file install CocoaPods.  From terminal
#    sudo gem install cocoapods
#    pod setup
# then close the Duffy project in XCode and in Duffy directory type 
#    pod install
#    open MyProject.xcworkspace
# From now on use Duffy.xcworkspace

xcodeproj '../Duffy.xcodeproj'

platform :ios, '7.0' 
inhibit_all_warnings!

pod 'RestKit', '~> 0.20.0'
pod 'JDStatusBarNotification', '~> 1.4.7'
pod 'CocoaLumberjack', '~> 1.8.1'

