COMMAND_PICK = 0
COMMAND_CLEAR = 1
COMMAND_FETCH = 2
COMMAND_ADD = 3
COMMAND_REMIND = 4
COMMAND_DELETE = 5
COMMAND_ACTIVATE = 6
COMMAND_LIST = 7
COMMAND_HELP = 8

STATE_NORMAL = 'normal'
STATE_TUTORIAL = 'tutorial'
STATE_NOT_ACTIVATED = 'not-activated'
STATE_REMIND = 'remind'
STATE_DELETE = 'delete'
STATE_ADD = 'add'