import datetime

PIPELINE_LOCAL_BASE_PATH = "/var/duffy/user_data/"
PIPELINE_REMOTE_HOST = 'duffy@titanblack.duffyapp.com'
PIPELINE_REMOTE_PATH = '/home/duffy/pipeline/staging'

THUMBNAIL_SIZE = 156

STATE_NEW = 0
STATE_COPIED = 1
STATE_CLASSIFIED = 2

DEFAULT_CLUSTER_THRESHOLD = 80
DEFAULT_DUP_THRESHOLD = 40
DEFAULT_MINUTES_TO_CLUSTER = 5

# iOS Notifications

IOS_NOTIFICATIONS_AUTHENTICATION = 'AuthNone'
IOS_NOTIFICATIONS_DEV_APNS_HOSTNAME = 'gateway.sandbox.push.apple.com'
IOS_NOTIFICATIONS_DEV_APNS_SERVICENAME = 'StrandDev'

IOS_NOTIFICATIONS_PROD_APNS_HOSTNAME = 'gateway.push.apple.com'
IOS_NOTIFICATIONS_PROD_APNS_SERVICENAME = 'StrandProd'

IOS_NOTIFICATIONS_DEV_APNS_ID = 1
IOS_NOTIFICATIONS_PROD_APNS_ID = 2
IOS_NOTIFICATIONS_DEREK_DEV_APNS_ID = 3
IOS_NOTIFICATIONS_ENTERPRISE_PROD_APNS_ID = 4
IOS_NOTIFICATIONS_ENTERPRISE_DEV_APNS_ID = 5

IOS_NOTIFICATIONS_RESULT_ERROR = 0
IOS_NOTIFICATIONS_RESULT_SENT = 1
IOS_NOTIFICATIONS_RESULT_NOT_SENT = 2

NOTIFICATIONS_NEW_PHOTO_ID = 1
NOTIFICATIONS_JOIN_STRAND_ID = 2
NOTIFICATIONS_PHOTO_FAVORITED_ID = 3
NOTIFICATIONS_FETCH_GPS_ID = 4
NOTIFICATIONS_RAW_FIRESTARTER_ID = 5
NOTIFICATIONS_PHOTO_FIRESTARTER_ID = 6
NOTIFICATIONS_REFRESH_FEED = 7
NOTIFICATIONS_SOCKET_REFRESH_FEED = 8
NOTIFICATIONS_INVITED_TO_STRAND = 9
NOTIFICATIONS_ACCEPTED_INVITE = 10
NOTIFICATIONS_RETRO_FIRESTARTER = 11
NOTIFICATIONS_UNACCEPTED_INVITE_FS = 12
NOTIFICATIONS_PHOTO_COMMENT = 13

# This is really 1-6
NOTIFICATIONS_ANY = range(1,7)

NOTIFICATIONS_SOUND_DICT = {
	NOTIFICATIONS_NEW_PHOTO_ID : 'default',
	NOTIFICATIONS_JOIN_STRAND_ID : 'default',
	NOTIFICATIONS_PHOTO_FAVORITED_ID : 'default',
	NOTIFICATIONS_FETCH_GPS_ID : None,
	NOTIFICATIONS_RAW_FIRESTARTER_ID : None,
	NOTIFICATIONS_PHOTO_FIRESTARTER_ID : 'default',
	NOTIFICATIONS_REFRESH_FEED : None,
	NOTIFICATIONS_INVITED_TO_STRAND : 'default',
	NOTIFICATIONS_ACCEPTED_INVITE : 'default',
	NOTIFICATIONS_RETRO_FIRESTARTER : 'default',
	NOTIFICATIONS_UNACCEPTED_INVITE_FS : None,
	NOTIFICATIONS_PHOTO_COMMENT : 'default',
}

NOTIFICATIONS_VIZ_DICT = {
	NOTIFICATIONS_NEW_PHOTO_ID : True,
	NOTIFICATIONS_JOIN_STRAND_ID : True,
	NOTIFICATIONS_PHOTO_FAVORITED_ID : True,
	NOTIFICATIONS_FETCH_GPS_ID : False,
	NOTIFICATIONS_RAW_FIRESTARTER_ID : True,
	NOTIFICATIONS_PHOTO_FIRESTARTER_ID : True,
	NOTIFICATIONS_REFRESH_FEED : False,
	NOTIFICATIONS_INVITED_TO_STRAND : True,
	NOTIFICATIONS_ACCEPTED_INVITE : True,
	NOTIFICATIONS_RETRO_FIRESTARTER : True,
	NOTIFICATIONS_UNACCEPTED_INVITE_FS : True,
	NOTIFICATIONS_PHOTO_COMMENT : True,
}

NOTIFICATIONS_CUSTOM_DICT = {
	NOTIFICATIONS_NEW_PHOTO_ID : {'type': NOTIFICATIONS_NEW_PHOTO_ID, 'view': 1},
	NOTIFICATIONS_JOIN_STRAND_ID : {'type': NOTIFICATIONS_JOIN_STRAND_ID, 'view': 0},
	NOTIFICATIONS_PHOTO_FAVORITED_ID : {'type': NOTIFICATIONS_PHOTO_FAVORITED_ID, 'view': 0},
	NOTIFICATIONS_FETCH_GPS_ID : {'type': NOTIFICATIONS_FETCH_GPS_ID, 'fgps': 1},
	NOTIFICATIONS_RAW_FIRESTARTER_ID : {'type': NOTIFICATIONS_RAW_FIRESTARTER_ID}, 
	NOTIFICATIONS_PHOTO_FIRESTARTER_ID : {'type': NOTIFICATIONS_PHOTO_FIRESTARTER_ID},
	NOTIFICATIONS_REFRESH_FEED : {'type': NOTIFICATIONS_REFRESH_FEED, 'ff': 1},
	NOTIFICATIONS_INVITED_TO_STRAND : {'type': NOTIFICATIONS_INVITED_TO_STRAND},
	NOTIFICATIONS_ACCEPTED_INVITE : {'type': NOTIFICATIONS_ACCEPTED_INVITE},
	NOTIFICATIONS_RETRO_FIRESTARTER : {'type': NOTIFICATIONS_RETRO_FIRESTARTER},
	NOTIFICATIONS_UNACCEPTED_INVITE_FS : {'type': NOTIFICATIONS_UNACCEPTED_INVITE_FS},
	NOTIFICATIONS_PHOTO_COMMENT : {'type': NOTIFICATIONS_PHOTO_COMMENT},
}

NOTIFICATIONS_APP_VIEW_CAMERA = 0
NOTIFICATIONS_APP_VIEW_GALLERY = 1

TWILIO_ACCOUNT = "ACf7272766cd6e51024750c3a1395a6f2f"
TWILIO_TOKEN = "63eb729d07ec8980d5267cb6b715e06f"
TWILIO_PHONE_NUM = "16506662114"

DEV_PHONE_NUMBERS = ["+16508158274", "+19172827255", "+16505759014"]

# 3 hours
TIME_WITHIN_MINUTES_FOR_NEIGHBORING = 3 * 60
MINUTES_FOR_NOLOC_NEIGHBORING = 15

DISTANCE_WITHIN_METERS_FOR_ROUGH_NEIGHBORING = 750
DISTANCE_WITHIN_METERS_FOR_FINE_NEIGHBORING = 750

TIMEDELTA_FOR_STRANDING = datetime.timedelta(hours=3)

# links for inviting
INVITE_LINK_ENTERPRISE = 'bit.ly/1noDnx2' # bit.ly/strand-beta also works
INVITE_LINK_APP_STORE = 'bit.ly/strand-appstore'

FEED_OBJECT_TYPE_STRAND = 'section' # will be strand
FEED_OBJECT_TYPE_INVITE_STRAND = 'invite_strand'
FEED_OBJECT_TYPE_STRAND_POST = 'strand_post'
FEED_OBJECT_TYPE_STRAND_POSTS = 'strand_posts'
FEED_OBJECT_TYPE_LIKE_ACTION = 'like_action'
FEED_OBJECT_TYPE_SUGGESTED_PHOTOS = 'suggested_photos'
FEED_OBJECT_TYPE_STRAND_JOIN = 'strand_join'
FEED_OBJECT_TYPE_FRIENDS_LIST = 'friends_list'
FEED_OBJECT_TYPE_SWAP_SUGGESTION = 'section'

ACTION_TYPE_FAVORITE = 0
ACTION_TYPE_CREATE_STRAND = 1
ACTION_TYPE_ADD_PHOTOS_TO_STRAND = 2
ACTION_TYPE_JOIN_STRAND = 3
ACTION_TYPE_COMMENT = 4


