


typedef NSString *const DFPermissionType;
extern DFPermissionType DFPermissionRemoteNotifications;
extern DFPermissionType DFPermissionLocation;


typedef NSString *const DFPermissionStateType;

extern DFPermissionStateType DFPermissionStateNotRequested;
extern DFPermissionStateType DFPermissionStateGranted;
extern DFPermissionStateType DFPermissionStateDenied;
extern DFPermissionStateType DFPermissionStateUnavailable;
