# To use this file install CocoaPods.  From terminal
#    sudo gem install cocoapods
#    pod setup
# then close the Strand project in XCode and in this directory type
#    pod install
#    open Strand.xcworkspace
# From now on use Strand.xcworkspace

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Strand.xcodeproj'

platform :ios, '7.0' 
inhibit_all_warnings!

pod 'RestKit', '~> 0.20.0'
pod 'JDStatusBarNotification', '~> 1.4.7'
pod 'CocoaLumberjack', '~> 1.8.1'
pod 'HockeySDK', :git => 'https://github.com/bitstadium/HockeySDK-iOS.git'
pod 'MMPopLabel', :git => 'https://github.com/hbridge/MMPopLabel.git'
pod 'CRToast', '~> 0.0.7'
pod 'Localytics-iOS-Client', '~> 2.23.0'
pod 'FormKit.m', '~> 0.4.0'
pod 'SAMGradientView', '~> 0.2.1'
pod 'LKbadgeView', '~> 1.1.0'
pod 'WYPopoverController', '~> 0.2.2'
pod 'SVProgressHUD', :git => 'https://github.com/samvermette/SVProgressHUD.git'
pod 'RHAddressBook', '~> 1.1.1'
pod 'MCSwipeTableViewCell', '~> 2.1.2'
pod 'FMDB/FTS', '~> 2.4'
pod 'Slash', '~> 0.1.2'
pod 'UIColor+BFPaperColors', '~> 1.3.1'
pod 'GBFlatButton', '~> 2.1.0'
pod 'KLCPopup', '~> 1.0'